//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.544
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.544.
// 
#pragma warning disable 1591

namespace RAFClientDemo.RafProxy {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="RAFProxySoap", Namespace="http://tempuri.org/")]
    public partial class RAFProxy : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback CustomerInsertParamsOperationCompleted;
        
        private System.Threading.SendOrPostCallback CustomerInsertOperationCompleted;
        
        private System.Threading.SendOrPostCallback CustomerGetDetailsOperationCompleted;
        
        private System.Threading.SendOrPostCallback CustomerGetAssetsOperationCompleted;
        
        private System.Threading.SendOrPostCallback CustomerSearchParamsOperationCompleted;
        
        private System.Threading.SendOrPostCallback CustomerSearchStringOperationCompleted;
        
        private System.Threading.SendOrPostCallback CustomerSearchOperationCompleted;
        
        private System.Threading.SendOrPostCallback AssetInsertParamsOperationCompleted;
        
        private System.Threading.SendOrPostCallback AssetInsertStringOperationCompleted;
        
        private System.Threading.SendOrPostCallback AssetInsertOperationCompleted;
        
        private System.Threading.SendOrPostCallback testDBCnxOperationCompleted;
        
        private System.Threading.SendOrPostCallback guiGetFieldsByLanguageOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public RAFProxy() {
            this.Url = global::RAFClientDemo.Properties.Settings.Default.RAFClientDemo_RafProxy_RAFProxy;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CustomerInsertParamsCompletedEventHandler CustomerInsertParamsCompleted;
        
        /// <remarks/>
        public event CustomerInsertCompletedEventHandler CustomerInsertCompleted;
        
        /// <remarks/>
        public event CustomerGetDetailsCompletedEventHandler CustomerGetDetailsCompleted;
        
        /// <remarks/>
        public event CustomerGetAssetsCompletedEventHandler CustomerGetAssetsCompleted;
        
        /// <remarks/>
        public event CustomerSearchParamsCompletedEventHandler CustomerSearchParamsCompleted;
        
        /// <remarks/>
        public event CustomerSearchStringCompletedEventHandler CustomerSearchStringCompleted;
        
        /// <remarks/>
        public event CustomerSearchCompletedEventHandler CustomerSearchCompleted;
        
        /// <remarks/>
        public event AssetInsertParamsCompletedEventHandler AssetInsertParamsCompleted;
        
        /// <remarks/>
        public event AssetInsertStringCompletedEventHandler AssetInsertStringCompleted;
        
        /// <remarks/>
        public event AssetInsertCompletedEventHandler AssetInsertCompleted;
        
        /// <remarks/>
        public event testDBCnxCompletedEventHandler testDBCnxCompleted;
        
        /// <remarks/>
        public event guiGetFieldsByLanguageCompletedEventHandler guiGetFieldsByLanguageCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CustomerInsertParams", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode CustomerInsertParams() {
            object[] results = this.Invoke("CustomerInsertParams", new object[0]);
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void CustomerInsertParamsAsync() {
            this.CustomerInsertParamsAsync(null);
        }
        
        /// <remarks/>
        public void CustomerInsertParamsAsync(object userState) {
            if ((this.CustomerInsertParamsOperationCompleted == null)) {
                this.CustomerInsertParamsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCustomerInsertParamsOperationCompleted);
            }
            this.InvokeAsync("CustomerInsertParams", new object[0], this.CustomerInsertParamsOperationCompleted, userState);
        }
        
        private void OnCustomerInsertParamsOperationCompleted(object arg) {
            if ((this.CustomerInsertParamsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CustomerInsertParamsCompleted(this, new CustomerInsertParamsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CustomerInsert", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode CustomerInsert(System.Xml.XmlNode Params) {
            object[] results = this.Invoke("CustomerInsert", new object[] {
                        Params});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void CustomerInsertAsync(System.Xml.XmlNode Params) {
            this.CustomerInsertAsync(Params, null);
        }
        
        /// <remarks/>
        public void CustomerInsertAsync(System.Xml.XmlNode Params, object userState) {
            if ((this.CustomerInsertOperationCompleted == null)) {
                this.CustomerInsertOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCustomerInsertOperationCompleted);
            }
            this.InvokeAsync("CustomerInsert", new object[] {
                        Params}, this.CustomerInsertOperationCompleted, userState);
        }
        
        private void OnCustomerInsertOperationCompleted(object arg) {
            if ((this.CustomerInsertCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CustomerInsertCompleted(this, new CustomerInsertCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CustomerGetDetails", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet CustomerGetDetails(int custID, int langid) {
            object[] results = this.Invoke("CustomerGetDetails", new object[] {
                        custID,
                        langid});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void CustomerGetDetailsAsync(int custID, int langid) {
            this.CustomerGetDetailsAsync(custID, langid, null);
        }
        
        /// <remarks/>
        public void CustomerGetDetailsAsync(int custID, int langid, object userState) {
            if ((this.CustomerGetDetailsOperationCompleted == null)) {
                this.CustomerGetDetailsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCustomerGetDetailsOperationCompleted);
            }
            this.InvokeAsync("CustomerGetDetails", new object[] {
                        custID,
                        langid}, this.CustomerGetDetailsOperationCompleted, userState);
        }
        
        private void OnCustomerGetDetailsOperationCompleted(object arg) {
            if ((this.CustomerGetDetailsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CustomerGetDetailsCompleted(this, new CustomerGetDetailsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CustomerGetAssets", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet CustomerGetAssets(int custID, int langid) {
            object[] results = this.Invoke("CustomerGetAssets", new object[] {
                        custID,
                        langid});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void CustomerGetAssetsAsync(int custID, int langid) {
            this.CustomerGetAssetsAsync(custID, langid, null);
        }
        
        /// <remarks/>
        public void CustomerGetAssetsAsync(int custID, int langid, object userState) {
            if ((this.CustomerGetAssetsOperationCompleted == null)) {
                this.CustomerGetAssetsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCustomerGetAssetsOperationCompleted);
            }
            this.InvokeAsync("CustomerGetAssets", new object[] {
                        custID,
                        langid}, this.CustomerGetAssetsOperationCompleted, userState);
        }
        
        private void OnCustomerGetAssetsOperationCompleted(object arg) {
            if ((this.CustomerGetAssetsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CustomerGetAssetsCompleted(this, new CustomerGetAssetsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CustomerSearchParams", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode CustomerSearchParams() {
            object[] results = this.Invoke("CustomerSearchParams", new object[0]);
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void CustomerSearchParamsAsync() {
            this.CustomerSearchParamsAsync(null);
        }
        
        /// <remarks/>
        public void CustomerSearchParamsAsync(object userState) {
            if ((this.CustomerSearchParamsOperationCompleted == null)) {
                this.CustomerSearchParamsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCustomerSearchParamsOperationCompleted);
            }
            this.InvokeAsync("CustomerSearchParams", new object[0], this.CustomerSearchParamsOperationCompleted, userState);
        }
        
        private void OnCustomerSearchParamsOperationCompleted(object arg) {
            if ((this.CustomerSearchParamsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CustomerSearchParamsCompleted(this, new CustomerSearchParamsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CustomerSearchString", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet CustomerSearchString(string xmlString) {
            object[] results = this.Invoke("CustomerSearchString", new object[] {
                        xmlString});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void CustomerSearchStringAsync(string xmlString) {
            this.CustomerSearchStringAsync(xmlString, null);
        }
        
        /// <remarks/>
        public void CustomerSearchStringAsync(string xmlString, object userState) {
            if ((this.CustomerSearchStringOperationCompleted == null)) {
                this.CustomerSearchStringOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCustomerSearchStringOperationCompleted);
            }
            this.InvokeAsync("CustomerSearchString", new object[] {
                        xmlString}, this.CustomerSearchStringOperationCompleted, userState);
        }
        
        private void OnCustomerSearchStringOperationCompleted(object arg) {
            if ((this.CustomerSearchStringCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CustomerSearchStringCompleted(this, new CustomerSearchStringCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CustomerSearch", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet CustomerSearch(System.Xml.XmlNode Params) {
            object[] results = this.Invoke("CustomerSearch", new object[] {
                        Params});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void CustomerSearchAsync(System.Xml.XmlNode Params) {
            this.CustomerSearchAsync(Params, null);
        }
        
        /// <remarks/>
        public void CustomerSearchAsync(System.Xml.XmlNode Params, object userState) {
            if ((this.CustomerSearchOperationCompleted == null)) {
                this.CustomerSearchOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCustomerSearchOperationCompleted);
            }
            this.InvokeAsync("CustomerSearch", new object[] {
                        Params}, this.CustomerSearchOperationCompleted, userState);
        }
        
        private void OnCustomerSearchOperationCompleted(object arg) {
            if ((this.CustomerSearchCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CustomerSearchCompleted(this, new CustomerSearchCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AssetInsertParams", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode AssetInsertParams() {
            object[] results = this.Invoke("AssetInsertParams", new object[0]);
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void AssetInsertParamsAsync() {
            this.AssetInsertParamsAsync(null);
        }
        
        /// <remarks/>
        public void AssetInsertParamsAsync(object userState) {
            if ((this.AssetInsertParamsOperationCompleted == null)) {
                this.AssetInsertParamsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAssetInsertParamsOperationCompleted);
            }
            this.InvokeAsync("AssetInsertParams", new object[0], this.AssetInsertParamsOperationCompleted, userState);
        }
        
        private void OnAssetInsertParamsOperationCompleted(object arg) {
            if ((this.AssetInsertParamsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AssetInsertParamsCompleted(this, new AssetInsertParamsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AssetInsertString", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string AssetInsertString(string xmlString) {
            object[] results = this.Invoke("AssetInsertString", new object[] {
                        xmlString});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void AssetInsertStringAsync(string xmlString) {
            this.AssetInsertStringAsync(xmlString, null);
        }
        
        /// <remarks/>
        public void AssetInsertStringAsync(string xmlString, object userState) {
            if ((this.AssetInsertStringOperationCompleted == null)) {
                this.AssetInsertStringOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAssetInsertStringOperationCompleted);
            }
            this.InvokeAsync("AssetInsertString", new object[] {
                        xmlString}, this.AssetInsertStringOperationCompleted, userState);
        }
        
        private void OnAssetInsertStringOperationCompleted(object arg) {
            if ((this.AssetInsertStringCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AssetInsertStringCompleted(this, new AssetInsertStringCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AssetInsert", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode AssetInsert(System.Xml.XmlNode Params) {
            object[] results = this.Invoke("AssetInsert", new object[] {
                        Params});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void AssetInsertAsync(System.Xml.XmlNode Params) {
            this.AssetInsertAsync(Params, null);
        }
        
        /// <remarks/>
        public void AssetInsertAsync(System.Xml.XmlNode Params, object userState) {
            if ((this.AssetInsertOperationCompleted == null)) {
                this.AssetInsertOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAssetInsertOperationCompleted);
            }
            this.InvokeAsync("AssetInsert", new object[] {
                        Params}, this.AssetInsertOperationCompleted, userState);
        }
        
        private void OnAssetInsertOperationCompleted(object arg) {
            if ((this.AssetInsertCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AssetInsertCompleted(this, new AssetInsertCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/testDBCnx", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool testDBCnx() {
            object[] results = this.Invoke("testDBCnx", new object[0]);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void testDBCnxAsync() {
            this.testDBCnxAsync(null);
        }
        
        /// <remarks/>
        public void testDBCnxAsync(object userState) {
            if ((this.testDBCnxOperationCompleted == null)) {
                this.testDBCnxOperationCompleted = new System.Threading.SendOrPostCallback(this.OntestDBCnxOperationCompleted);
            }
            this.InvokeAsync("testDBCnx", new object[0], this.testDBCnxOperationCompleted, userState);
        }
        
        private void OntestDBCnxOperationCompleted(object arg) {
            if ((this.testDBCnxCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.testDBCnxCompleted(this, new testDBCnxCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/guiGetFieldsByLanguage", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode guiGetFieldsByLanguage(int languageID, string registrarID, string registrarKey) {
            object[] results = this.Invoke("guiGetFieldsByLanguage", new object[] {
                        languageID,
                        registrarID,
                        registrarKey});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void guiGetFieldsByLanguageAsync(int languageID, string registrarID, string registrarKey) {
            this.guiGetFieldsByLanguageAsync(languageID, registrarID, registrarKey, null);
        }
        
        /// <remarks/>
        public void guiGetFieldsByLanguageAsync(int languageID, string registrarID, string registrarKey, object userState) {
            if ((this.guiGetFieldsByLanguageOperationCompleted == null)) {
                this.guiGetFieldsByLanguageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnguiGetFieldsByLanguageOperationCompleted);
            }
            this.InvokeAsync("guiGetFieldsByLanguage", new object[] {
                        languageID,
                        registrarID,
                        registrarKey}, this.guiGetFieldsByLanguageOperationCompleted, userState);
        }
        
        private void OnguiGetFieldsByLanguageOperationCompleted(object arg) {
            if ((this.guiGetFieldsByLanguageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.guiGetFieldsByLanguageCompleted(this, new guiGetFieldsByLanguageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void CustomerInsertParamsCompletedEventHandler(object sender, CustomerInsertParamsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CustomerInsertParamsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CustomerInsertParamsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void CustomerInsertCompletedEventHandler(object sender, CustomerInsertCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CustomerInsertCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CustomerInsertCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void CustomerGetDetailsCompletedEventHandler(object sender, CustomerGetDetailsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CustomerGetDetailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CustomerGetDetailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void CustomerGetAssetsCompletedEventHandler(object sender, CustomerGetAssetsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CustomerGetAssetsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CustomerGetAssetsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void CustomerSearchParamsCompletedEventHandler(object sender, CustomerSearchParamsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CustomerSearchParamsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CustomerSearchParamsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void CustomerSearchStringCompletedEventHandler(object sender, CustomerSearchStringCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CustomerSearchStringCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CustomerSearchStringCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void CustomerSearchCompletedEventHandler(object sender, CustomerSearchCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CustomerSearchCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CustomerSearchCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void AssetInsertParamsCompletedEventHandler(object sender, AssetInsertParamsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AssetInsertParamsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AssetInsertParamsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void AssetInsertStringCompletedEventHandler(object sender, AssetInsertStringCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AssetInsertStringCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AssetInsertStringCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void AssetInsertCompletedEventHandler(object sender, AssetInsertCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AssetInsertCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AssetInsertCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void testDBCnxCompletedEventHandler(object sender, testDBCnxCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class testDBCnxCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal testDBCnxCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void guiGetFieldsByLanguageCompletedEventHandler(object sender, guiGetFieldsByLanguageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class guiGetFieldsByLanguageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal guiGetFieldsByLanguageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591