//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.239.
// 
#pragma warning disable 1591

namespace RafWS_Test.RafWS {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="RafQuerySoap", Namespace="http://api.ifar.biz/")]
    public partial class RafQuery : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetAssetRulesParamsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAssetRulesStringOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAssetRulesNoValStringOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAssetRulesOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public RafQuery() {
            this.Url = global::RafWS_Test.Properties.Settings.Default.RafWS_Test_RafWS_RafQuery;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetAssetRulesParamsCompletedEventHandler GetAssetRulesParamsCompleted;
        
        /// <remarks/>
        public event GetAssetRulesStringCompletedEventHandler GetAssetRulesStringCompleted;
        
        /// <remarks/>
        public event GetAssetRulesNoValStringCompletedEventHandler GetAssetRulesNoValStringCompleted;
        
        /// <remarks/>
        public event GetAssetRulesCompletedEventHandler GetAssetRulesCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute(Namespace="http://api.ifar.biz/")]
        public System.Xml.XmlNode GetAssetRulesParams() {
            object[] results = this.Invoke("GetAssetRulesParams", new object[0]);
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void GetAssetRulesParamsAsync() {
            this.GetAssetRulesParamsAsync(null);
        }
        
        /// <remarks/>
        public void GetAssetRulesParamsAsync(object userState) {
            if ((this.GetAssetRulesParamsOperationCompleted == null)) {
                this.GetAssetRulesParamsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAssetRulesParamsOperationCompleted);
            }
            this.InvokeAsync("GetAssetRulesParams", new object[0], this.GetAssetRulesParamsOperationCompleted, userState);
        }
        
        private void OnGetAssetRulesParamsOperationCompleted(object arg) {
            if ((this.GetAssetRulesParamsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAssetRulesParamsCompleted(this, new GetAssetRulesParamsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://api.ifar.biz/GetAssetRulesString", RequestNamespace="http://api.ifar.biz/", ResponseNamespace="http://api.ifar.biz/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetAssetRulesString(string xmlString) {
            object[] results = this.Invoke("GetAssetRulesString", new object[] {
                        xmlString});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetAssetRulesStringAsync(string xmlString) {
            this.GetAssetRulesStringAsync(xmlString, null);
        }
        
        /// <remarks/>
        public void GetAssetRulesStringAsync(string xmlString, object userState) {
            if ((this.GetAssetRulesStringOperationCompleted == null)) {
                this.GetAssetRulesStringOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAssetRulesStringOperationCompleted);
            }
            this.InvokeAsync("GetAssetRulesString", new object[] {
                        xmlString}, this.GetAssetRulesStringOperationCompleted, userState);
        }
        
        private void OnGetAssetRulesStringOperationCompleted(object arg) {
            if ((this.GetAssetRulesStringCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAssetRulesStringCompleted(this, new GetAssetRulesStringCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://api.ifar.biz/GetAssetRulesNoValString", RequestNamespace="http://api.ifar.biz/", ResponseNamespace="http://api.ifar.biz/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetAssetRulesNoValString(string xmlString) {
            object[] results = this.Invoke("GetAssetRulesNoValString", new object[] {
                        xmlString});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetAssetRulesNoValStringAsync(string xmlString) {
            this.GetAssetRulesNoValStringAsync(xmlString, null);
        }
        
        /// <remarks/>
        public void GetAssetRulesNoValStringAsync(string xmlString, object userState) {
            if ((this.GetAssetRulesNoValStringOperationCompleted == null)) {
                this.GetAssetRulesNoValStringOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAssetRulesNoValStringOperationCompleted);
            }
            this.InvokeAsync("GetAssetRulesNoValString", new object[] {
                        xmlString}, this.GetAssetRulesNoValStringOperationCompleted, userState);
        }
        
        private void OnGetAssetRulesNoValStringOperationCompleted(object arg) {
            if ((this.GetAssetRulesNoValStringCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAssetRulesNoValStringCompleted(this, new GetAssetRulesNoValStringCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://api.ifar.biz/GetAssetRules", RequestNamespace="http://api.ifar.biz/", ResponseNamespace="http://api.ifar.biz/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode GetAssetRules(System.Xml.XmlNode Params) {
            object[] results = this.Invoke("GetAssetRules", new object[] {
                        Params});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void GetAssetRulesAsync(System.Xml.XmlNode Params) {
            this.GetAssetRulesAsync(Params, null);
        }
        
        /// <remarks/>
        public void GetAssetRulesAsync(System.Xml.XmlNode Params, object userState) {
            if ((this.GetAssetRulesOperationCompleted == null)) {
                this.GetAssetRulesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAssetRulesOperationCompleted);
            }
            this.InvokeAsync("GetAssetRules", new object[] {
                        Params}, this.GetAssetRulesOperationCompleted, userState);
        }
        
        private void OnGetAssetRulesOperationCompleted(object arg) {
            if ((this.GetAssetRulesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAssetRulesCompleted(this, new GetAssetRulesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetAssetRulesParamsCompletedEventHandler(object sender, GetAssetRulesParamsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAssetRulesParamsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAssetRulesParamsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetAssetRulesStringCompletedEventHandler(object sender, GetAssetRulesStringCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAssetRulesStringCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAssetRulesStringCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetAssetRulesNoValStringCompletedEventHandler(object sender, GetAssetRulesNoValStringCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAssetRulesNoValStringCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAssetRulesNoValStringCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetAssetRulesCompletedEventHandler(object sender, GetAssetRulesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAssetRulesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAssetRulesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591